DROP TABLE IF EXISTS mpas, films, users, genres, film_genres, film_likes, friendships, directors, film_directors CASCADE;

CREATE TABLE IF NOT EXISTS mpas (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS films (
      id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name varchar NOT NULL,
      description text(200) NOT NULL,
      duration integer,
      release_date date,
      mpa_id integer REFERENCES mpas (id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS directors (
    id 		INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS film_directors (
    id 		INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id     INTEGER REFERENCES films (id) ON DELETE CASCADE,
    director_id INTEGER REFERENCES directors (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS users (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar NOT NULL,
    login varchar NOT NULL,
    name varchar,
    birthday date NOT NULL
);

CREATE TABLE IF NOT EXISTS genres (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS film_genres (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id integer REFERENCES films (id) ON DELETE CASCADE,
    genre_id integer REFERENCES genres (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS film_likes (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id integer REFERENCES films (id) ON DELETE CASCADE,
    user_id integer
);

CREATE TABLE IF NOT EXISTS friendships (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_sender_id integer REFERENCES users (id) ON DELETE CASCADE,
    user_recipient_id integer REFERENCES users (id) ON DELETE CASCADE
);
